letseat/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView

from letseat import views
from restaurants import urls as restaurant_urls

urlpatterns = [
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    url(r'^accounts/login/*$', RedirectView.as_view(url='/login_or_register', permanent=True)),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^restaurants/', include(restaurant_urls, namespace='restaurants')),

    url(r'^/*$', views.index, name='index'),
    url(r'^register/*$', views.register, name='register'),
    url(r'^login_or_register/*$', views.login_or_register, name='login_or_register'),
    url(r'^login/*$', views.login, name='login'),
    url(r'^logout/*$', views.logout, name='logout'),
    url(r'^home/*$', views.home, name='home'),
]

restaurants/urls.py
from django.conf.urls import include, url

from restaurants import views


urlpatterns = [
    url(r'^/*$', views.index, name='index'),
    url(r'^new/*$', views.new, name='new'),
    url(r'^edit/(?P<pk>\d+)/*$', views.edit, name='edit'),
    url(r'^delete/(?P<pk>\d+)/*$', views.delete, name='delete'),
]

restaurants/models.py
from django.contrib.auth.models import User
from django.db import models


class Restaurant(models.Model):
    created_by = models.ForeignKey(User, related_name='restaurant_created_by')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, related_name='restaurant_modified_by')
    modified_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=32, unique=True)
    phone_number = models.CharField(max_length=16)
    address = models.TextField()
    menus = models.URLField()
    logo = models.URLField()

    class Meta:
        ordering = ['name']

letseat/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.template.response import TemplateResponse
from django.views.decorators.http import require_GET, require_POST


def index(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('home'))
    else:
        return HttpResponseRedirect(reverse('login_or_register'))


def login_or_register(request):
    return TemplateResponse(request, 'login_or_register.html')


@require_POST
def register(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    confirm = request.POST.get('confirm')
    messages = []
    if not username or not password or not confirm:
        messages.append('All fields are required!')
        return TemplateResponse(request, 'login_or_register.html', {'messages': messages, 'register_tab': True})
    if password != confirm:
        messages.append('Passwords did not match!')
        return TemplateResponse(request, 'login_or_register.html', {'messages': messages, 'register_tab': True})
    try:
        User.objects.create_user(username=username, password=password)
    except IntegrityError:
        messages.append('That username is already taken!')
        return TemplateResponse(request, 'login_or_register.html', {'messages': messages, 'register_tab': True})
    user = auth.authenticate(username=username, password=password)
    auth.login(request, user)
    return TemplateResponse(request, 'home.html')


@require_POST
def login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = auth.authenticate(username=username, password=password)
    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect(reverse('home'))
    else:
        return HttpResponseRedirect(reverse('login'))


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def home(request):
    return TemplateResponse(request, 'home.html')

restaurants/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.response import TemplateResponse

from restaurants.models import Restaurant


def index(request):
    restaurants = Restaurant.objects.all()
    print restaurants
    return TemplateResponse(request, 'index.html', {'restaurants': restaurants})


def new(request):
    if request.method == 'POST':
        name = request.POST.get('restaurant_name')
        if not name:
            return TemplateResponse(request, 'new.html', {'messages': ['Name is a required field!']})
        phone_number = request.POST.get('phone_number')
        address = request.POST.get('address')
        menu = request.POST.get('menu')
        logo = request.POST.get('logo')
        Restaurant.objects.create(created_by=request.user, modified_by= request.user, name=name.strip(),
                                  phone_number=phone_number, address=address, menu=menu, logo=logo)
        return HttpResponseRedirect(reverse('restaurants:index'))
    return TemplateResponse(request, 'new.html')


def edit(request, pk):
    restaurant = Restaurant.objects.get(pk=pk)
    if request.method == 'POST':
        restaurant.phone_number = request.POST.get('phone_number')
        restaurant.address = request.POST.get('address')
        restaurant.menu = request.POST.get('menu')
        restaurant.logo = request.POST.get('logo')
        restaurant.save()
        return HttpResponseRedirect(reverse('restaurants:index'))
    return TemplateResponse(request, 'edit.html', {'restaurant': restaurant})


def delete(request, pk):
    Restaurant.objects.get(pk=pk).delete()
    return HttpResponseRedirect(reverse('restaurants:index'))

restaurants/templates/edit.html
{% extends "base.html" %}

{% block content %}
    <div class="content-padded">
        <form action="{% url 'restaurants:edit' pk=restaurant.pk %}" method="POST">
            {% csrf_token %}
            <label class="btn btn-positive btn-block btn-outlined">{{ restaurant.name }}</label>
            <input type="text" name="phone_number" placeholder="Phone Number" {% if restaurant.phone_number %}value="{{ restaurant.phone_number }}"{% endif %}>
            <input type="text" name="address" placeholder="Address" {% if restaurant.address %}value="{{ restaurant.address }}"{% endif %}>
            <input type="text" name="menu" placeholder="Menu" {% if restaurant.menu %}value="{{ restaurant.menu }}"{% endif %}>
            <input type="text" name="logo" placeholder="Logo" {% if restaurant.logo %}value="{{ restaurant.logo }}"{% endif %}>
            <button class="btn btn-positive btn-block">Save</button>
            <a href="{% url 'restaurants:index' %}" class="btn btn-negative btn-block">Cancel</a>
            <a href="{% url 'restaurants:delete' pk=restaurant.pk %}" class="btn btn-negative btn-block btn-outlined">Delete</a>
        </form>
    </div>
{% endblock %}

restaurants/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% if request.user.is_staff %}
        <div class="content-padded"><a href="{% url 'restaurants:new' %}"><button class="btn btn-block btn-positive">Add a new restaurant</button></a></div>
    {% endif %}
    <ul class="table-view">
        {% for restaurant in restaurants %}
            <li class="table-view-cell"><a href="{% url 'restaurants:edit' pk=restaurant.pk %}">{{ restaurant.name }}<button class="btn btn-negative btn-outlined">0</button></a></li>
        {% endfor %}
        <li class="table-view-divider">Placeholders</li>
        <li class="table-view-cell">Placeholder 1<button class="btn btn-positive btn-outlined">1</button></li>
        <li class="table-view-cell">Placeholder 2<button class="btn btn-negative btn-outlined">0</button></li>
        <li class="table-view-cell">Placeholder 3<button class="btn btn-primary btn-outlined">2</button></li>
    </ul>
{% endblock %}

restaurants/templates/new.html
{% extends "base.html" %}

{% block content %}
    <div class="content-padded">
        <form action="{% url 'restaurants:new' %}" method="POST">
            {% csrf_token %}
            <label class="btn btn-positive btn-block btn-outlined">New Restaurant</label>
            <input type="text" name="restaurant_name" placeholder="Name" required>
            <input type="text" name="phone_number" placeholder="Phone Number">
            <input type="text" name="address" placeholder="Address">
            <input type="text" name="menu" placeholder="Menu">
            <input type="text" name="logo" placeholder="Logo">
            <button class="btn btn-positive btn-block">Save</button>
            <a href="{% url 'restaurants:index' %}" class="btn btn-negative btn-block">Cancel</a>
        </form>
    </div>
{% endblock %}